Repository Team-Wable/WABLE-iOS, pull requests merged in 2024-08, with the labels that each got.

#4 Setting [#3] 와블 깃허브 초기세팅
  .github/ISSUE_TEMPLATE/wable-issue-template.md
  PULL_REQUEST_TEMPLATE.md
Labels: Setting, 🐢상우

#14 Feat [#13] #6 브랜치 복구 버전
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/Global/Extention/UIApplication+.swift
  Wable-iOS/Global/Extention/UIButton+.swift
  Wable-iOS/Global/Extention/UIViewController+.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Network/Home/ResponseDTO/FeedDetailReplyDTO.swift
  Wable-iOS/Network/Home/ResponseDTO/HomeFeedListDTO.swift
  Wable-iOS/Presentation/Helpers/WablePopupView.swift
  Wable-iOS/Presentation/Home/Supports/Team.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  Wable-iOS/Presentation/Home/Views/Cells/FeedDetailTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/FeedDetailView.swift
  Wable-iOS/Presentation/Home/Views/HomeView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomWriteView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedContentView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedDetailBottomView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedInfoView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/HomeTabView.swift
  Wable-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Wable-iOS/Presentation/TabBar/WableTabBarItem.swift
  Wable-iOS/Presentation/Write/ViewController/WriteViewController.swift
Labels: Feat

#16 Feat [#15] InfoMatch UI 구현 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Extention/UILabel+.swift
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_info.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_info.imageset/ic_info.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_info.imageset/ic_info@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_info.imageset/ic_info@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_versus.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_versus.imageset/Frame 1000013323.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_versus.imageset/Frame 1000013323@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_versus.imageset/Frame 1000013323@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/tbd.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Team/tbd.imageset/img_empty.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/tbd.imageset/img_empty@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/tbd.imageset/img_empty@3x.png
  Wable-iOS/Network/Info/TeamMatchDTO.swift
  Wable-iOS/Presentation/Home/Supports/Team.swift
  Wable-iOS/Presentation/Info/Supports/MatchProgress.swift
  Wable-iOS/Presentation/Info/View/Cells/MatchSessionTableViewCell.swift
  Wable-iOS/Presentation/Info/View/Cells/MatchTableViewCell.swift
  Wable-iOS/Presentation/Info/View/Cells/MatchTableViewHeaderView.swift
  Wable-iOS/Presentation/Info/View/InfoView.swift
  Wable-iOS/Presentation/Info/View/MatchView.swift
  Wable-iOS/Presentation/Info/View/SubViews/ATeamView.swift
  Wable-iOS/Presentation/Info/View/SubViews/BTeamView.swift
  Wable-iOS/Presentation/Info/View/SubViews/InfoTabView.swift
  Wable-iOS/Presentation/Info/View/SubViews/MatchProgressStatusView.swift
  Wable-iOS/Presentation/Info/View/SubViews/TeamScoreView.swift
  Wable-iOS/Presentation/Info/ViewController/InfoMatchViewController.swift
  Wable-iOS/Presentation/Info/ViewController/InfoViewController.swift
Labels: Feat

#22 Feat [#21] 글쓰기 뷰, 마이페이지(게시글, 댓글) 뷰 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Extention/UITextView+.swift
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Button/btn_remove_photo.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Button/btn_remove_photo.imageset/btn_remove_photo.png
  Wable-iOS/Global/Resources/Assets.xcassets/Button/btn_remove_photo.imageset/btn_remove_photo@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Button/btn_remove_photo.imageset/btn_remove_photo@3x.png
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/Views/Cells/FeedDetailTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/FeedDetailView.swift
  Wable-iOS/Presentation/Home/Views/HomeView.swift
  Wable-iOS/Presentation/MyPage/View/MyPageView.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageAccountInfoViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageEditProfileViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPagePostViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageReplyViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSettingAlarmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutConfirmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageAccountInfoViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageProfileViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageSignOutConfirmViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageSignOutReasonViewModel.swift
  Wable-iOS/Presentation/TabBar/WableTabBarController.swift
  Wable-iOS/Presentation/Write/View/WriteTextView.swift
  Wable-iOS/Presentation/Write/View/WriteView.swift
  Wable-iOS/Presentation/Write/ViewController/WriteViewController.swift
  Wable-iOS/Presentation/Write/ViewModel/WriteViewModel.swift
Labels: Feat, 🐢상우

#24 Network [#23] 애플로그인 및 로그인, 회원가입 API 연동
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Application/SceneDelegate.swift
  Wable-iOS/Global/Extention/UIImageView+.swift
  Wable-iOS/Global/Protocol/NetworkServiceType.swift
  Wable-iOS/Global/Resources/Info.plist
  Wable-iOS/Network/Foundation/URLSession/BaseResponse.swift
  Wable-iOS/Network/Foundation/URLSession/Empty.swift
  Wable-iOS/Network/Foundation/URLSession/HttpMethod.swift
  Wable-iOS/Network/Foundation/URLSession/NetworkError.swift
  Wable-iOS/Network/Foundation/URLSession/NetworkService.swift
  Wable-iOS/Network/MyPage/DTO/RequestDTO/MyPageMemberDeleteDTO.swift
  Wable-iOS/Network/MyPage/DTO/ResponseDTO/MyPageAccountInfoResponseDTO.swift
  Wable-iOS/Network/MyPage/DTO/ResponseDTO/MyPageMemberCommentResponseDTO.swift
  Wable-iOS/Network/MyPage/DTO/ResponseDTO/MyPageMemberContentResponseDTO.swift
  Wable-iOS/Network/MyPage/DTO/ResponseDTO/MypageProfileResponseDTO.swift
  Wable-iOS/Network/SocialLogin/DTO/RequestDTO/SocialLoginRequestDTO.swift
  Wable-iOS/Network/SocialLogin/DTO/ResponseDTO/SocialLoginResponseDTO.swift
  Wable-iOS/Network/TokenManager/TokenManager.swift
  Wable-iOS/Network/TokenManager/TokenReissueResponseDTO.swift
  Wable-iOS/Network/UserProfile/DTO/RequestDTO/UserProfileUnionRequestDTO.swift
  Wable-iOS/Presentation/Helpers/UserInfo.swift
  Wable-iOS/Presentation/Join/View/JoinLCKTeamView.swift
  Wable-iOS/Presentation/Join/View/JoinLCKYearView.swift
  Wable-iOS/Presentation/Join/View/JoinProfileView.swift
  Wable-iOS/Presentation/Join/ViewController/JoinAgreementViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinLCKTeamViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinLCKYearViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinProfileViewController.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinAgreementViewModel.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinProfileViewModel.swift
  Wable-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Wable-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  Wable-iOS/Presentation/MyPage/View/MyPageView.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageAccountInfoViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutConfirmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageSignOutConfirmViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Wable-iOS/Presentation/TabBar/WableTabBarController.swift
  Wable-iOS/Presentation/TabBar/WableTabBarItem.swift
  Wable-iOS/Wable-iOS.entitlements
Labels: Network, 🐢상우
