Repository Team-Wable/WABLE-iOS, pull requests merged in 2024-09, with the labels that each got.

#28 Network [#27] 알림 탭 API 연결 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Extention/String+.swift
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_ranking.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_ranking.imageset/Group 1000013042.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_ranking.imageset/Group 1000013042@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_ranking.imageset/Group 1000013042@3x.png
  Wable-iOS/Network/Info/InfoAPI.swift
  Wable-iOS/Network/Info/InfoRouter.swift
  Wable-iOS/Network/Info/ResponseDTO/TodayMatchesDTO.swift
  Wable-iOS/Network/Info/TeamMatchDTO.swift
  Wable-iOS/Network/Notification/NotificationAPI.swift
  Wable-iOS/Network/Notification/NotificationRouter.swift
  Wable-iOS/Network/Notification/ResponseDTO/ActivityNotificationDTO.swift
  Wable-iOS/Network/Notification/ResponseDTO/InfoNotificationDTO.swift
  Wable-iOS/Presentation/Home/Supports/Team.swift
  Wable-iOS/Presentation/Info/View/InfoView.swift
  Wable-iOS/Presentation/Info/View/RankingView.swift
  Wable-iOS/Presentation/Info/ViewController/InfoMatchViewController.swift
  Wable-iOS/Presentation/Info/ViewController/InfoRankingViewController.swift
  Wable-iOS/Presentation/Info/ViewModels/InfoMatchViewModel.swift
  Wable-iOS/Presentation/Notification/Supports/NotiActivityText.swift
  Wable-iOS/Presentation/Notification/Supports/NotiInfoText.swift
  Wable-iOS/Presentation/Notification/View/Cells/NotificationTableViewCell.swift
  Wable-iOS/Presentation/Notification/View/NotificationView.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationActivityViewController.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationInformationViewController.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationActivityViewModel.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationInfoViewModel.swift
Labels: Network

#32 Feat [#30] 1차 QA 사항 반영
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_info_box.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_info_box.imageset/img_info_box.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_info_box.imageset/img_info_box@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_info_box.imageset/img_info_box@3x.png
  Wable-iOS/Presentation/Helpers/WablePopupView.swift
  Wable-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  Wable-iOS/Presentation/MyPage/View/MyPageEditProfileView.swift
  Wable-iOS/Presentation/MyPage/View/MyPageProfileView.swift
  Wable-iOS/Presentation/MyPage/View/MyPageView.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageEditProfileViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPagePostViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/Write/View/WriteTextView.swift
Labels: Feat, 🐢상우

#33 Fix [#31] 홈 및 알림 QA 이슈 반영
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/Views/HomeView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/HomeTabView.swift
  Wable-iOS/Presentation/Info/View/InfoView.swift
  Wable-iOS/Presentation/Info/View/MatchView.swift
  Wable-iOS/Presentation/Info/View/SubViews/InfoTabView.swift
Labels: Fix

#36 Fix [#34] 댓글 TextField관련 이슈 제외한 2차 QA 반영 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/xcshareddata/xcschemes/Wable-iOS.xcscheme
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_noti_empty.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_noti_empty.imageset/Frame 1000013614.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_noti_empty.imageset/Frame 1000013614@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_noti_empty.imageset/Frame 1000013614@3x.png
  Wable-iOS/Network/Foundation/APIConstants.swift
  Wable-iOS/Network/Home/ResponseDTO/HomeFeedListDTO.swift
  Wable-iOS/Network/Notification/NotificationAPI.swift
  Wable-iOS/Network/Notification/NotificationRouter.swift
  Wable-iOS/Network/Notification/ResponseDTO/HomeFeedContentDTO.swift
  Wable-iOS/Presentation/Helpers/WablePopupView.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/Views/Cells/FeedDetailTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/HomeView.swift
  Wable-iOS/Presentation/Info/View/MatchView.swift
  Wable-iOS/Presentation/Info/ViewController/InfoMatchViewController.swift
  Wable-iOS/Presentation/Notification/Supports/NotiActivityText.swift
  Wable-iOS/Presentation/Notification/Supports/UserProfile.swift
  Wable-iOS/Presentation/Notification/View/Cells/NotificationTableViewCell.swift
  Wable-iOS/Presentation/Notification/View/NotificationContentView.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationActivityViewController.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationInformationViewController.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationViewController.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationActivityViewModel.swift
Labels: Fix, 🍪윤빈

#37 Feat [#35] 2차 QA 반영 및 남은 기능 구현 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Network/Foundation/APIConstants.swift
  Wable-iOS/Network/Foundation/BaseAPI.swift
  Wable-iOS/Network/Foundation/MoyaLoggingPlugin.swift
  Wable-iOS/Network/Foundation/URLSession/NetworkService.swift
  Wable-iOS/Network/Home/RequestDTO/CommentLikeRequestDTO.swift
  Wable-iOS/Network/Home/ResponseDTO/FeedDetailResponseDTO.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/FeedDetailViewModel.swift
  Wable-iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  Wable-iOS/Presentation/Home/ViewModels/LikeViewModel.swift
  Wable-iOS/Presentation/Home/Views/Cells/FeedDetailTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/FeedDetailView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomWriteView.swift
  Wable-iOS/Presentation/Info/ViewModels/InfoMatchViewModel.swift
  Wable-iOS/Presentation/MyPage/View/MyPageView.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPagePostViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageReplyViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationActivityViewModel.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationInfoViewModel.swift
  Wable-iOS/Presentation/Write/View/WriteView.swift
  Wable-iOS/Presentation/Write/ViewController/WriteViewController.swift
Labels: Feat, 🐢상우

#39 Fix [#38] 리젝 관련 이슈 해결
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/Views/HomeView.swift
  Wable-iOS/Presentation/Info/View/InfoView.swift
  Wable-iOS/Presentation/Info/View/MatchView.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationViewController.swift
Labels: Fix, 🍪윤빈

#41 Feat [#40] QA 사항 반영 및 토스트 메시지, 환영 메시지 기능 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_ghost.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_ghost.imageset/toast_ghost.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_ghost.imageset/toast_ghost@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_ghost.imageset/toast_ghost@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_report.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_report.imageset/toast_report.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_report.imageset/toast_report@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_report.imageset/toast_report@3x.png
  Wable-iOS/Presentation/Helpers/WablePopupView.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/LikeViewModel.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomWriteView.swift
  Wable-iOS/Presentation/Join/ViewController/JoinAgreementViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinLCKTeamViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinLCKYearViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinProfileViewController.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinAgreementViewModel.swift
  Wable-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Wable-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  Wable-iOS/Presentation/MyPage/Cell/MyPageAccountInfoTableViewCell.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageEditProfileViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPagePostViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageReplyViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSettingAlarmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutConfirmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/Write/View/WriteTextView.swift
  Wable-iOS/Presentation/Write/View/WriteView.swift
  Wable-iOS/Presentation/Write/ViewController/WriteViewController.swift
  Wable-iOS/Presentation/Write/ViewModel/WriteViewModel.swift
Labels: Feat, 🐢상우

#44 Feat [#43] QA 사항 모두 반영 및 토스트메시지, 팝업뷰 모두 구현 완료
  Wable-iOS/Application/SceneDelegate.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Shared/AppStoreCheckManager.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinAgreementViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinProfileViewController.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinAgreementViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageEditProfileViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPagePostViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageReplyViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageProfileViewModel.swift
  Wable-iOS/Presentation/TabBar/WableTabBarItem.swift
  Wable-iOS/Presentation/Write/ViewController/WriteViewController.swift
Labels: Feat, 🐢상우

#45 Feat [#42] 푸시알림 구현 및 사진 상세보기, cell 재사용 문제 해결
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/Application/AppDelegate.swift
  Wable-iOS/Global/Extention/UIImageView+.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Info.plist
  Wable-iOS/Network/Foundation/APIConstants.swift
  Wable-iOS/Network/Home/HomeAPI.swift
  Wable-iOS/Network/Home/HomeRouter.swift
  Wable-iOS/Presentation/Helpers/WablePhotoDetailView.swift
  Wable-iOS/Presentation/Helpers/WablePushAlarmHelper.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedContentView.swift
  Wable-iOS/Presentation/Notification/View/Cells/NotificationTableViewCell.swift
  Wable-iOS/Presentation/Notification/View/NotificationView.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationActivityViewController.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationActivityViewModel.swift
  Wable-iOS/Wable-iOS.entitlements
Labels: Feat
