Repository Team-Wable/WABLE-iOS, pull requests merged in 2024-10, with the labels that each got.

#48 Fix [#47] QA 사항 반영
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/FeedDetailViewModel.swift
  Wable-iOS/Presentation/Join/ViewController/JoinLCKTeamViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSettingAlarmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/Write/ViewController/WriteViewController.swift
Labels: Fix, 🐢상우

#49 Fix [#46] 공식 릴리즈 홍보 전 QA 반영 및 앰플리튜드 심기
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_ghost.imageset/toast_ghost.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_ghost.imageset/toast_ghost@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_ghost.imageset/toast_ghost@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_progress.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_progress.imageset/toast.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_progress.imageset/toast@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_progress.imageset/toast@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_progress.imageset/toast_progress.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_progress.imageset/toast_progress@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_progress.imageset/toast_progress@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_report.imageset/toast_report.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_report.imageset/toast_report@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_report.imageset/toast_report@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_success.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_success.imageset/toast.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_success.imageset/toast@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_success.imageset/toast@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_success.imageset/toast_success.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_success.imageset/toast_success@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_success.imageset/toast_success@3x.png
  Wable-iOS/Global/Resources/Info.plist
  Wable-iOS/Global/Shared/AmplitudeManager.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/FeedDetailViewModel.swift
  Wable-iOS/Presentation/Home/Views/Cells/FeedDetailTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomWriteView.swift
  Wable-iOS/Presentation/Info/ViewController/InfoViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinProfileViewController.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinAgreementViewModel.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinLCKTeamViewModel.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinLCKYearViewModel.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinProfileViewModel.swift
  Wable-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageEditProfileViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutConfirmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageAccountInfoViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageSignOutConfirmViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageSignOutReasonViewModel.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationViewController.swift
  Wable-iOS/Presentation/TabBar/WableTabBarController.swift
  Wable-iOS/Presentation/Write/ViewController/WriteViewController.swift
  Wable-iOS/Presentation/Write/ViewModel/WriteViewModel.swift
Labels: Fix

#51 Fix [#50] 1.0.1 버전 버그 수정 및 1.0.2 업데이트 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/Application/AppDelegate.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/FeedDetailViewModel.swift
  Wable-iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  Wable-iOS/Presentation/Info/ViewController/InfoViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinProfileViewController.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinAgreementViewModel.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationActivityViewController.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationViewController.swift
  Wable-iOS/Presentation/TabBar/WableTabBarController.swift
Labels: Fix, 🍪윤빈

#53 Fix [#52] 버전 1.0.3을 위한 버그 수정
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Application/AppDelegate.swift
  Wable-iOS/Application/SceneDelegate.swift
  Wable-iOS/Global/Extention/UIView+.swift
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Tag/tag_Dk.imageset/Team=Dk.png
  Wable-iOS/Global/Resources/Assets.xcassets/Tag/tag_Dk.imageset/Team=Dk@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Tag/tag_Dk.imageset/Team=Dk@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_agreement_loading.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_agreement_loading.imageset/toast.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_agreement_loading.imageset/toast@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Toast/toast_agreement_loading.imageset/toast@3x.png
  Wable-iOS/Presentation/Helpers/CopyableLabel.swift
  Wable-iOS/Presentation/Helpers/WablePushAlarmHelper.swift
  Wable-iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  Wable-iOS/Presentation/Home/Views/Cells/FeedDetailTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedContentView.swift
  Wable-iOS/Presentation/Join/ViewController/JoinAgreementViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPagePostViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageReplyViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationViewController.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationActivityViewModel.swift
  Wable-iOS/Presentation/Splash/SplashViewController.swift
Labels: Fix, 🍪윤빈
