Repository Team-Wable/WABLE-iOS, pull requests merged in 2024-11, with the labels that each got.

#56 [Fix] #55 소식, 알림 탭 오류 및 로직 수정
  .gitignore
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Resources/wable_loading.json
  Wable-iOS/Global/Resources/wable_splash.json
  Wable-iOS/Network/Foundation/MoyaLoggingPlugin.swift
  Wable-iOS/Network/Info/ResponseDTO/TodayMatchesDTO.swift
  Wable-iOS/Network/Notification/NotificationAPI.swift
  Wable-iOS/Network/Notification/NotificationRouter.swift
  Wable-iOS/Network/Notification/ResponseDTO/ActivityNotificationDTO.swift
  Wable-iOS/Presentation/Helpers/CancelBag.swift
  Wable-iOS/Presentation/Helpers/ReuseIdentifiable.swift
  Wable-iOS/Presentation/Info/View/Cells/MatchSessionTableViewCell.swift
  Wable-iOS/Presentation/Info/View/Cells/MatchTableViewCell.swift
  Wable-iOS/Presentation/Info/View/Cells/MatchTableViewHeaderView.swift
  Wable-iOS/Presentation/Info/View/MatchView.swift
  Wable-iOS/Presentation/Info/View/SubViews/ATeamView.swift
  Wable-iOS/Presentation/Info/View/SubViews/BTeamView.swift
  Wable-iOS/Presentation/Info/View/SubViews/InfoTabView.swift
  Wable-iOS/Presentation/Info/View/SubViews/MatchProgressStatusView.swift
  Wable-iOS/Presentation/Info/View/SubViews/TeamScoreView.swift
  Wable-iOS/Presentation/Info/ViewController/InfoMatchViewController.swift
  Wable-iOS/Presentation/Info/ViewModels/InfoMatchViewModel.swift
  Wable-iOS/Presentation/Notification/Supports/NotiActivityText.swift
  Wable-iOS/Presentation/Notification/Supports/UserProfile.swift
  Wable-iOS/Presentation/Notification/View/Cells/NotificationTableViewCell.swift
  Wable-iOS/Presentation/Notification/View/NotificationContentView.swift
  Wable-iOS/Presentation/Notification/View/NotificationSegmentedControl.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationActivityViewController.swift
  Wable-iOS/Presentation/Notification/ViewController/NotificationViewController.swift
  Wable-iOS/Presentation/Notification/ViewModels/NotificationActivityViewModel.swift
Labels: Fix, 🍻 진웅

#59 Fix [#54] 제목 깨짐 현상 해결
  Wable-iOS/Presentation/Home/Views/Cells/HomeFeedTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedContentView.swift
Labels: Fix, 🍪윤빈

#58 Setting [#57] CombineCocoa 설치 및 폴더링
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS.xcodeproj/xcshareddata/xcschemes/Wable-iOS.xcscheme
  Wable-iOS/Application/AppDelegate.swift
  Wable-iOS/Global/Extention/Publisher+UIControl.swift
  Wable-iOS/Global/Extention/UIFont+.swift
  Wable-iOS/Global/Extention/UIImageView+.swift
  Wable-iOS/Global/Extention/UITextField+.swift
  Wable-iOS/Global/Extention/UIView+.swift
  Wable-iOS/Global/Shared/AmplitudeManager.swift
  Wable-iOS/Global/Shared/AppStoreCheckManager.swift
  Wable-iOS/Global/Utils/CancelBag.swift
  Wable-iOS/Global/Utils/Functions.swift
  Wable-iOS/Global/Utils/ReuseIdentifiable.swift
  Wable-iOS/Global/Utils/UserInfo.swift
  Wable-iOS/Presentation/Helpers/WableToastView.swift
  Wable-iOS/Presentation/UIComponents/BackButton.swift
  Wable-iOS/Presentation/UIComponents/CopyableLabel.swift
  Wable-iOS/Presentation/UIComponents/HambergerButton.swift
  Wable-iOS/Presentation/UIComponents/WableButton.swift
  Wable-iOS/Presentation/UIComponents/WablePhotoDetailView.swift
  Wable-iOS/Presentation/UIComponents/WablePopupView.swift
  Wable-iOS/Presentation/UIComponents/WablePushAlarmHelper.swift
  Wable-iOS/Presentation/UIComponents/XButton.swift
Labels: Setting, 🍻 진웅

#64 Refactor [#63] 소식 탭 페이징 및 세그먼트 컨트롤 정상화
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Extention/Adjusted+.swift
  Wable-iOS/Presentation/Info/View/InfoSegmentedControl.swift
  Wable-iOS/Presentation/Info/View/InfoView.swift
  Wable-iOS/Presentation/Info/View/SubViews/InfoLogoView.swift
  Wable-iOS/Presentation/Info/View/SubViews/InfoTabView.swift
  Wable-iOS/Presentation/Info/ViewController/InfoViewController.swift
  Wable-iOS/Presentation/UIComponents/WableSegmentedControl.swift
Labels: Refactor, 🍻 진웅

#66 Feat [#65] 순위 뷰 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Network/Info/InfoAPI.swift
  Wable-iOS/Network/Info/InfoRouter.swift
  Wable-iOS/Network/Info/ResponseDTO/LCKGameTypeDTO.swift
  Wable-iOS/Network/Info/ResponseDTO/LCKTeamRankDTO.swift
  Wable-iOS/Presentation/Info/Match/Support/MatchProgress.swift
  Wable-iOS/Presentation/Info/Match/View/Cell/MatchSessionTableViewCell.swift
  Wable-iOS/Presentation/Info/Match/View/Cell/MatchTableViewCell.swift
  Wable-iOS/Presentation/Info/Match/View/Cell/MatchTableViewHeaderView.swift
  Wable-iOS/Presentation/Info/Match/View/MatchView.swift
  Wable-iOS/Presentation/Info/Match/View/SubView/ATeamView.swift
  Wable-iOS/Presentation/Info/Match/View/SubView/BTeamView.swift
  Wable-iOS/Presentation/Info/Match/View/SubView/MatchProgressStatusView.swift
  Wable-iOS/Presentation/Info/Match/View/SubView/TeamScoreView.swift
  Wable-iOS/Presentation/Info/Match/ViewController/InfoMatchViewController.swift
  Wable-iOS/Presentation/Info/Match/ViewModel/InfoMatchViewModel.swift
  Wable-iOS/Presentation/Info/Page/View/InfoView.swift
  Wable-iOS/Presentation/Info/Page/View/SubView/InfoLogoView.swift
  Wable-iOS/Presentation/Info/Page/ViewController/InfoViewController.swift
  Wable-iOS/Presentation/Info/Ranking/Support/TeamImageMapper.swift
  Wable-iOS/Presentation/Info/Ranking/View/Cell/RankCell.swift
  Wable-iOS/Presentation/Info/Ranking/View/Cell/RankHeaderView.swift
  Wable-iOS/Presentation/Info/Ranking/View/Cell/SessionCell.swift
  Wable-iOS/Presentation/Info/Ranking/View/RankingView.swift
  Wable-iOS/Presentation/Info/Ranking/ViewController/InfoRankingViewController.swift
  Wable-iOS/Presentation/Info/Ranking/ViewModel/InfoRankingViewModel.swift
  Wable-iOS/Presentation/Info/View/RankingView.swift
  Wable-iOS/Presentation/Info/ViewController/InfoRankingViewController.swift
Labels: Feat, 🍻 진웅

#68 Feat [#61] 대댓글 뷰 및 서버통신 구현 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/Global/Extention/UIButton+.swift
  Wable-iOS/Global/Extention/UIViewController+.swift
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_gray.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_gray.imageset/Status=Default, Size=S.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_gray.imageset/Status=Default, Size=S@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_gray.imageset/Status=Default, Size=S@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_press_small.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_press_small.imageset/Status=Press, Size=S.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_press_small.imageset/Status=Press, Size=S@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_heart_press_small.imageset/Status=Press, Size=S@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_ripple_reply.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_ripple_reply.imageset/ic_ripple_reply.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_ripple_reply.imageset/ic_ripple_reply@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Icon/ic_ripple_reply.imageset/ic_ripple_reply@3x.png
  Wable-iOS/Network/Home/HomeAPI.swift
  Wable-iOS/Network/Home/HomeRouter.swift
  Wable-iOS/Network/Home/RequestDTO/WriteReplyRequestDTO.swift
  Wable-iOS/Network/Home/ResponseDTO/FeedDetailReplyDTO.swift
  Wable-iOS/Network/MyPage/DTO/ResponseDTO/MyPageMemberCommentResponseDTO.swift
  Wable-iOS/Presentation/Home/Model/FlattenReplyModel.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/FeedDetailViewModel.swift
  Wable-iOS/Presentation/Home/Views/Cells/FeedDetailTableViewCell.swift
  Wable-iOS/Presentation/Home/Views/FeedDetailView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedBottomWriteView.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedDetailBottomView.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageReplyViewController.swift
Labels: Feat, 🍪윤빈

#72 Feat [#67] 소식 탭 뉴스 뷰 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Extention/UIViewController+.swift
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_newsbanner.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_newsbanner.imageset/img_newsbanner.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_newsbanner.imageset/img_newsbanner@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Image/img_newsbanner.imageset/img_newsbanner@3x.png
  Wable-iOS/Network/Info/InfoAPI.swift
  Wable-iOS/Network/Info/InfoRouter.swift
  Wable-iOS/Network/Info/ResponseDTO/NewsDTO.swift
  Wable-iOS/Presentation/Home/ViewController/FeedDetailViewController.swift
  Wable-iOS/Presentation/Info/Detail/View/InfoDetailView.swift
  Wable-iOS/Presentation/Info/Detail/ViewController/ImagePopupViewController.swift
  Wable-iOS/Presentation/Info/Detail/ViewController/InfoDetailViewController.swift
  Wable-iOS/Presentation/Info/News/Support/NewsTimeFormatter.swift
  Wable-iOS/Presentation/Info/News/View/Cell/NewsCell.swift
  Wable-iOS/Presentation/Info/News/View/Cell/NewsHeaderView.swift
  Wable-iOS/Presentation/Info/News/View/InfoNewsView.swift
  Wable-iOS/Presentation/Info/News/ViewController/InfoNewsViewController.swift
  Wable-iOS/Presentation/Info/News/ViewModel/InfoNewsViewModel.swift
  Wable-iOS/Presentation/Info/Page/View/InfoView.swift
  Wable-iOS/Presentation/Info/Page/ViewController/InfoViewController.swift
  Wable-iOS/Presentation/Info/Ranking/View/RankingView.swift
  Wable-iOS/Presentation/Join/ViewController/JoinProfileViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageEditProfileViewController.swift
Labels: Feat, 🍻 진웅

#74 Feat [#73] 소식 탭 공지사항 뷰 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Network/Info/InfoAPI.swift
  Wable-iOS/Network/Info/InfoRouter.swift
  Wable-iOS/Network/Info/ResponseDTO/NoticeDTO.swift
  Wable-iOS/Presentation/Info/Detail/View/InfoDetailView.swift
  Wable-iOS/Presentation/Info/Detail/ViewController/InfoDetailViewController.swift
  Wable-iOS/Presentation/Info/Notice/Support/NoticeTimeFormatter.swift
  Wable-iOS/Presentation/Info/Notice/View/Cell/NoticeCell.swift
  Wable-iOS/Presentation/Info/Notice/View/InfoNoticeView.swift
  Wable-iOS/Presentation/Info/Notice/ViewController/InfoNoticeViewController.swift
  Wable-iOS/Presentation/Info/Notice/ViewModel/InfoNoticeViewModel.swift
  Wable-iOS/Presentation/Info/Page/View/InfoView.swift
  Wable-iOS/Presentation/Info/Page/ViewController/InfoViewController.swift
Labels: Feat, 🍻 진웅

#78 Fix [#77] 소식 탭 QA 반영 및 경기 정보 뷰 수정
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Network/Info/ResponseDTO/TodayMatchesDTO.swift
  Wable-iOS/Presentation/Info/Detail/View/InfoDetailView.swift
  Wable-iOS/Presentation/Info/Detail/ViewController/ImagePopupViewController.swift
  Wable-iOS/Presentation/Info/Match/Support/TodayMatchesDateFormatter.swift
  Wable-iOS/Presentation/Info/Match/View/Cell/MatchSessionTableViewCell.swift
  Wable-iOS/Presentation/Info/Match/ViewController/InfoMatchViewController.swift
  Wable-iOS/Presentation/Info/Match/ViewModel/InfoMatchViewModel.swift
  Wable-iOS/Presentation/Info/Page/ViewController/InfoViewController.swift
Labels: Fix, 🍻 진웅
