Repository Team-Wable/WABLE-iOS, pull requests merged in 2025-04, with the labels that each got.

#157 [Refactor] String 익스텐션 수정
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Helper/Extension/AttributedString+.swift
  Wable-iOS/Presentation/Helper/Extension/NSMutableAttributedString+.swift
  Wable-iOS/Presentation/Helper/Extension/String+.swift
  Wable-iOS/Presentation/Onboarding/View/AgreementItemView.swift
  Wable-iOS/Presentation/Overview/Rank/View/RankListViewController.swift
  Wable-iOS/Presentation/WableComponent/Youjin/TabBar/NavigationViewController.swift
Labels: ✨ feat, ♻️ refactor, 🍻 진웅

#160 [Fix] UITextField 익스텐션 메서드 수정
  Wable-iOS/Presentation/Helper/Extension/UITextField+.swift
  Wable-iOS/Presentation/Onboarding/View/ProfileRegisterView.swift
Labels: 🛠️ fix, ♻️ refactor

#163 [Add] 디자인 시스템을 반영한 색상 추가
  Wable-iOS/Resource/Color.xcassets/GrayScale/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray100.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray200.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray300.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray400.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray500.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray600.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray700.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray800.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/gray900.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/wableBlack.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/GrayScale/wableWhite.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Primary/Contents.json
  Wable-iOS/Resource/Color.xcassets/Primary/Purple50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Primary/purple10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Primary/purple100.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Secondary/Contents.json
  Wable-iOS/Resource/Color.xcassets/Secondary/blue10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Secondary/blue50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Secondary/sky10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Secondary/sky50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/System/Contents.json
  Wable-iOS/Resource/Color.xcassets/System/error.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/System/info.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/System/success.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/System/warning.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/bro10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/bro50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/dk10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/dk50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/drx10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/drx50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/gen10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/gen50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/hle10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/hle50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/kt10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/kt50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/ns10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/ns50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/t110.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/t150.colorset/Contents.json
Labels: 🧀 add

#174 [Chore] 커스텀 네비게이션 바의 애니메이션뷰 높이, 위치 수정
  Wable-iOS/Presentation/WableComponent/Navigation/NavigationView.swift
Labels: 🦴 chore, 🍻 진웅

#176 [Fix] 1차 QA 반영
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Helper/Extension/UITextView+.swift
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/Home/View/WritePostViewController.swift
  Wable-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/LCKYearViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/ProfileRegisterViewController.swift
  Wable-iOS/Presentation/WableComponent/Cell/CommentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/Cell/ContentCollectionViewCell.swift
Labels: 🛠️ fix, 🦉 유진
