Repository Team-Wable/WABLE-iOS, pull requests merged in 2025-06, with the labels that each got.

#221 [Fix] 홈 화면 QA 대응
  Wable-iOS/Presentation/Home/View/HomeViewController.swift
  Wable-iOS/Presentation/WableComponent/Cell/CommentCollectionViewCell.swift
Labels: 🛠️ fix, 🍻 진웅

#225 [Fix] 상세 화면 댓글 작성 뷰 로직 수정
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/WableComponent/Cell/CommentCollectionViewCell.swift
Labels: 🛠️ fix, 🦉 유진

#235 [Feat] 프로필 수정 기능 및 키보드 표시/숨김 처리에 따른 뷰 핸들링 익스텐션 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Enum/DefaultProfileType.swift
  Wable-iOS/Presentation/Helper/Extension/UIViewController+KeyboardHandling.swift
  Wable-iOS/Presentation/Onboarding/View/LCKTeamView.swift
  Wable-iOS/Presentation/Onboarding/ViewController/LCKTeamViewController.swift
  Wable-iOS/Presentation/Profile/Edit/ProfileEditView.swift
  Wable-iOS/Presentation/Profile/Edit/ProfileEditViewController.swift
  Wable-iOS/Presentation/WableComponent/Navigation/NavigationView.swift
  Wable-iOS/Presentation/WableComponent/View/TeamCollectionView.swift
Labels: ✨ feat, 🦉 유진

#239 [Feat] 투명도 안내를 위한 툴팁 구현하기
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Core/Literals/String/StringLiterals+Ghost.swift
  Wable-iOS/Presentation/Profile/Component/GhostInfoTooltipView.swift
  Wable-iOS/Presentation/Profile/Component/ProfileInfoCell.swift
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_info.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_info.imageset/ic_ghost_info.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_info.imageset/ic_ghost_info@2x.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_info.imageset/ic_ghost_info@3x.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_ghost_tooltip.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Image/img_ghost_tooltip.imageset/img_ghost_tooltip.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_ghost_tooltip.imageset/img_ghost_tooltip@2x.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_ghost_tooltip.imageset/img_ghost_tooltip@3x.png
Labels: ✨ feat, 🍻 진웅

#234 [Fix] 커뮤니티 탭 에러 수정
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/App/AppDelegate+InjectDependency.swift
  Wable-iOS/Data/RepositoryImpl/CommunityRepositoryImpl.swift
  Wable-iOS/Domain/RepositoryInterface/CommunityRepository.swift
  Wable-iOS/Domain/UseCase/Community/CommunityUseCase.swift
  Wable-iOS/Presentation/Community/View/CommunityViewController.swift
  Wable-iOS/Presentation/Community/View/Subview/CommunityView.swift
  Wable-iOS/Presentation/Community/ViewModel/CommunityViewModel.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
Labels: 🛠️ fix, 🍻 진웅

#247 [Feat] 글 작성 시 화면 상단으로 이동하는 로직 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Home/View/HomeViewController.swift
  Wable-iOS/Presentation/Home/View/WritePostViewController.swift
Labels: ✨ feat, 🦉 유진

#249 [Refactor] 정기회의 이후 요청사항 적용
  Wable-iOS/Core/Amplitude/AmplitudeManager.swift
  Wable-iOS/Core/Literals/String/StringLiterals+Ghost.swift
  Wable-iOS/Presentation/Profile/Component/ProfileInfoCell.swift
  Wable-iOS/Presentation/WableComponent/ViewController/PhotoDetailViewController.swift
Labels: ♻️ refactor

#251 [Add] 변경된 팀 브랜딩에 따른 색상 추가
  Wable-iOS/Resource/Color.xcassets/GrayScale/alpha50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/bfx10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/bfx50.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/dnf10.colorset/Contents.json
  Wable-iOS/Resource/Color.xcassets/Team/dnf50.colorset/Contents.json
Labels: 🧀 add, 🍻 진웅

#254 [Feat] 로그인 에러 토스트 구현, LoginViewModel 메서드 분리 및 코드 리팩토링
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Domain/Error/WableError.swift
  Wable-iOS/Domain/UseCase/Onboarding/UpdateFCMTokenUseCase.swift
  Wable-iOS/Domain/UseCase/Onboarding/UserProfileUseCase.swift
  Wable-iOS/Infra/Auth/AppleAuthProvider.swift
  Wable-iOS/Infra/Auth/KakaoAuthProvider.swift
  Wable-iOS/Infra/Local/UserDefaultsStorage.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Login/LoginViewModel.swift
  Wable-iOS/Presentation/Onboarding/ViewController/AgreementViewController.swift
  Wable-iOS/Presentation/Profile/Edit/ProfileEditViewController.swift
  Wable-iOS/Presentation/Profile/My/View/MyProfileViewController.swift
  Wable-iOS/Presentation/Profile/Withdrawal/Guide/View/WithdrawalGuideViewController.swift
Labels: 🛠️ fix, ♻️ refactor, 🦉 유진
