Repository Team-Wable/WABLE-iOS, pull requests merged in 2025-09, with the labels that each got.

#273 [Fix] 알림 목록 중 프로필 관련 터치 이벤트
  Wable-iOS/Presentation/Notification/Activity/View/ActivityNotificationViewController.swift
  Wable-iOS/Presentation/Notification/Activity/ViewModel/ActivityNotificationViewModel.swift
Labels: 🛠️ fix, 🍻 진웅

#272 [Feat] Fastlane 자동 배포 환경 구축
  .gitignore
  ExportOptions.plist
  Gemfile
  Gemfile.lock
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Resource/Info.plist
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/README.md
Labels: ✨ feat, 🦉 유진

#276 [Refactor] 뷰잇에 코디네이터 패턴 적용
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Core/Coordinator/Coordinator.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Presentation/Viewit/Coordinator/ViewitCoordinator.swift
  Wable-iOS/Presentation/Viewit/Create/View/CreateViewitViewController.swift
  Wable-iOS/Presentation/Viewit/List/View/ViewitListViewController.swift
Labels: ♻️ refactor

#281 [Refactor] FCM 토큰 업데이트 로직 간소화
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Presentation/Onboarding/ViewController/LCKYearViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewModel/AgreementViewModel.swift
Labels: ♻️ refactor, 🦉 유진
