Repository Team-Wable/WABLE-iOS, pull requests merged in 2025-03, with the labels that each got.

#107 [Fix] EventMonitor의 저장 프로퍼티 관련 경고 해결
  Wable-iOS/Infra/Network/OAuth/OAuthErrorMonitor.swift
Labels: 🛠️ fix, 🦉 유진

#109 [Feat] UserDefaults 정보 저장을 위한 UserSession 기능 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Data/RepositoryImpl/UserSessionRepositoryImpl.swift
  Wable-iOS/Domain/Entity/UserSession.swift
  Wable-iOS/Domain/RepositoryInterface/UserSessionRepository.swift
  Wable-iOS/Infra/Keychain/KeychainError.swift
  Wable-iOS/Infra/Local/KeychainStorage.swift
  Wable-iOS/Infra/Local/LocalError.swift
  Wable-iOS/Infra/Local/LocalKeyValueStorage.swift
  Wable-iOS/Infra/Local/UserDefaultsStorage.swift
  Wable-iOS/Infra/Network/APIProvider.swift
  Wable-iOS/Infra/Network/OAuth/OAuthenticator.swift
  Wable-iOS/Infra/Token/TokenError.swift
  Wable-iOS/Infra/Token/TokenStorage.swift
Labels: ✨ feat, 🦉 유진

#111 [Feat] 폰트 자간, 행간 적용을 위한 익스텐션 및 기타 UI 익스텐션 작성
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Interface/ViewModelType.swift
  Wable-iOS/Presentation/UIHelper/ReuseIdentifiable.swift
  Wable-iOS/Presentation/UIHelper/ScreenAdjustable.swift
  Wable-iOS/Presentation/UIHelper/String+.swift
  Wable-iOS/Presentation/UIHelper/UIFont+.swift
  Wable-iOS/Presentation/UIHelper/UIStackView+.swift
  Wable-iOS/Presentation/UIHelper/UITextField+.swift
  Wable-iOS/Presentation/UIHelper/UIView+.swift
Labels: ✨ feat, 🍻 진웅

#117 [Setting] TestFlight 배포 자동화를 위한 Github Actions 도입
  .github/secrets/TL_Distribution.p12.gpg
  .github/secrets/Wable_AppStore.mobileprovision.gpg
  .github/workflows/main.yml
  ExportOptions.plist
  Wable-iOS.xcodeproj/project.pbxproj
Labels: ⚙️ setting, 🦉 유진

#122 [Feat] 와블 컴포넌트(액션 시트, 404, 로딩뷰, 사진 상세, CTA버튼) 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/WableComponent/Jinung/LoadingViewController.swift
  Wable-iOS/Presentation/WableComponent/Jinung/NotFoundViewController.swift
  Wable-iOS/Presentation/WableComponent/Jinung/PhotoDetailViewController.swift
  Wable-iOS/Presentation/WableComponent/Jinung/WableActionSheetViewController.swift
  Wable-iOS/Presentation/WableComponent/Jinung/WableButton.swift
  Wable-iOS/Presentation/WableComponent/Jinung/jinung.swift
  Wable-iOS/Resource/Assets.xcassets/Image/img_error.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Image/img_error.imageset/img_error.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_error.imageset/img_error@2x.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_error.imageset/img_error@3x.png
Labels: ✨ feat, 🍻 진웅

#121 [Feat] 내리기, 좋아요, 댓글 UIButton 및 게시물, 댓글 CollectionViewCell 컴포넌트 작성
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/Data/Mapper/CommentMapper.swift
  Wable-iOS/Domain/Entity/CommentInfo.swift
  Wable-iOS/Domain/Entity/Opacity.swift
  Wable-iOS/Domain/Enum/LCKTeam.swift
  Wable-iOS/Presentation/Enum/AuthorType.swift
  Wable-iOS/Presentation/Enum/LottieType.swift
  Wable-iOS/Presentation/UIHelper/UIColor+.swift
  Wable-iOS/Presentation/WableComponent/Youjin/Button/CommentButton.swift
  Wable-iOS/Presentation/WableComponent/Youjin/Button/GhostButton.swift
  Wable-iOS/Presentation/WableComponent/Youjin/Button/LikeButton.swift
  Wable-iOS/Presentation/WableComponent/Youjin/Cell/CommentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/Youjin/Cell/ContentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/Youjin/TabBar/NavigationView.swift
  Wable-iOS/Presentation/WableComponent/Youjin/TabBar/TabBarController.swift
  Wable-iOS/Presentation/WableComponent/Youjin/View/PostUserInfoView.swift
  Wable-iOS/Presentation/WableComponent/Youjin/View/ToastView.swift
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_default.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_default.imageset/Status=Default-4.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_default.imageset/Status=Default@2x-4.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_default.imageset/Status=Default@3x-4.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_default.imageset/ic_ghost.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_default.imageset/ic_ghost@2x.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_ghost_default.imageset/ic_ghost@3x.png
Labels: ✨ feat, 🦉 유진

#125 [Feat] 스플래시 및 로그인 UI 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Splash/SplashViewController.swift
  Wable-iOS/Resource/Assets.xcassets/Image/img_login_background.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Image/img_login_background.imageset/iPhone 13 mini - 347.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_login_background.imageset/iPhone 13 mini - 347@2x.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_login_background.imageset/iPhone 13 mini - 347@3x.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_login_background.imageset/img_login_background.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_login_background.imageset/img_login_background@2x.png
  Wable-iOS/Resource/Assets.xcassets/Image/img_login_background.imageset/img_login_background@3x.png
Labels: ✨ feat, 🦉 유진

#127 [Feat] 와블 바텀 시트 구현 및 액션 시트 코드 수정
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/WableComponent/Jinung/WableActionSheetViewController.swift
  Wable-iOS/Presentation/WableComponent/Jinung/WableBottomSheetController.swift
  Wable-iOS/Presentation/WableComponent/Jinung/WableSheetViewController.swift
Labels: ✨ feat, ♻️ refactor, 🍻 진웅

#129 [Hotfix] 테스트를 위한 메인 전환 로직 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Onboarding/LCKYearView.swift
  Wable-iOS/Presentation/Onboarding/LCKYearViewController.swift
  Wable-iOS/Presentation/WableComponent/Youjin/TabBar/NavigationViewController.swift
Labels: 🦉 유진

#133 [Hotfix] NavigationView 수정
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/WableComponent/Youjin/TabBar/NavigationView.swift
  Wable-iOS/Presentation/WableComponent/Youjin/TabBar/NavigationViewController.swift
  Wable-iOS/Presentation/WableComponent/Youjin/TabBar/TabBarController.swift
Labels: 🛠️ fix, 🦉 유진

#134 [Setting] Presentation 폴더링
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Community/CommunityViewController.swift
  Wable-iOS/Presentation/Home/HomeViewController.swift
  Wable-iOS/Presentation/Notification/NotificationEmpty.swift
  Wable-iOS/Presentation/Overview/OverviewViewController.swift
  Wable-iOS/Presentation/Profile/ProfileViewController.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Presentation/UIHelper/UIView+.swift
  Wable-iOS/Presentation/UIHelper/UIViewController+.swift
  Wable-iOS/Presentation/Viewit/ViewitViewController.swift
  Wable-iOS/Presentation/WableComponent/Button/CommentButton.swift
  Wable-iOS/Presentation/WableComponent/Button/GhostButton.swift
  Wable-iOS/Presentation/WableComponent/Button/LikeButton.swift
  Wable-iOS/Presentation/WableComponent/Button/WableButton.swift
  Wable-iOS/Presentation/WableComponent/Cell/CommentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/Cell/ContentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/Navigation/NavigationView.swift
  Wable-iOS/Presentation/WableComponent/Navigation/NavigationViewController.swift
  Wable-iOS/Presentation/WableComponent/View/PostUserInfoView.swift
  Wable-iOS/Presentation/WableComponent/View/ToastView.swift
  Wable-iOS/Presentation/WableComponent/ViewController/LoadingViewController.swift
  Wable-iOS/Presentation/WableComponent/ViewController/NotFoundViewController.swift
  Wable-iOS/Presentation/WableComponent/ViewController/PhotoDetailViewController.swift
  Wable-iOS/Presentation/WableComponent/ViewController/WableBottomSheetController.swift
  Wable-iOS/Presentation/WableComponent/ViewController/WableSheetViewController.swift
Labels: ⚙️ setting, 🍻 진웅

#136 [Hotfix] NavigationViewController 초기화 메서드 파라미터 수정
  Wable-iOS/Presentation/WableComponent/Navigation/NavigationViewController.swift
Labels: 🛠️ fix, 🦉 유진

#140 [Feat] 소식 탭 화면 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Overview/Detail/View/AnnouncementDetailViewController.swift
  Wable-iOS/Presentation/Overview/Detail/View/Subview/AnnouncementDetailView.swift
  Wable-iOS/Presentation/Overview/GameSchedule/Model/GameStatus+.swift
  Wable-iOS/Presentation/Overview/GameSchedule/View/Cell/GameScheduleCell.swift
  Wable-iOS/Presentation/Overview/GameSchedule/View/Cell/GameScheduleHeaderView.swift
  Wable-iOS/Presentation/Overview/GameSchedule/View/GameScheduleListViewController.swift
  Wable-iOS/Presentation/Overview/GameSchedule/View/Subview/GameScheduleEmptyView.swift
  Wable-iOS/Presentation/Overview/News/View/Cell/NewsCell.swift
  Wable-iOS/Presentation/Overview/News/View/Cell/NewsHeaderView.swift
  Wable-iOS/Presentation/Overview/News/View/NewsViewController.swift
  Wable-iOS/Presentation/Overview/Notice/View/Cell/NoticeCell.swift
  Wable-iOS/Presentation/Overview/Notice/View/NoticeViewController.swift
  Wable-iOS/Presentation/Overview/OverviewViewController.swift
  Wable-iOS/Presentation/Overview/Page/OverviewPageViewController.swift
  Wable-iOS/Presentation/Overview/Rank/View/Cell/RankCell.swift
  Wable-iOS/Presentation/Overview/Rank/View/Cell/RankHeaderView.swift
  Wable-iOS/Presentation/Overview/Rank/View/RankListViewController.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Presentation/UIHelper/Date+.swift
  Wable-iOS/Presentation/UIHelper/Types.swift
  Wable-iOS/Presentation/UIHelper/UIView+.swift
  Wable-iOS/Presentation/WableComponent/Cell/GameTypeCell.swift
Labels: ✨ feat, 🍻 진웅

#144 [Feat] 소식 탭 뷰모델 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Data/RepositoryImpl/InformationRepositoryImpl.swift
  Wable-iOS/Presentation/Overview/Detail/View/Subview/AnnouncementDetailView.swift
  Wable-iOS/Presentation/Overview/GameSchedule/Model/GameScheduleViewItem.swift
  Wable-iOS/Presentation/Overview/GameSchedule/View/Cell/GameScheduleCell.swift
  Wable-iOS/Presentation/Overview/GameSchedule/View/Cell/GameScheduleHeaderView.swift
  Wable-iOS/Presentation/Overview/GameSchedule/View/GameScheduleListViewController.swift
  Wable-iOS/Presentation/Overview/GameSchedule/ViewModel/GameScheduleViewModel.swift
  Wable-iOS/Presentation/Overview/News/View/Cell/NewsCell.swift
  Wable-iOS/Presentation/Overview/News/View/Cell/NewsHeaderView.swift
  Wable-iOS/Presentation/Overview/News/View/NewsViewController.swift
  Wable-iOS/Presentation/Overview/News/ViewModel/NewsViewModel.swift
  Wable-iOS/Presentation/Overview/Notice/View/Cell/NoticeCell.swift
  Wable-iOS/Presentation/Overview/Notice/View/NoticeViewController.swift
  Wable-iOS/Presentation/Overview/Notice/ViewModel/NoticeViewModel.swift
  Wable-iOS/Presentation/Overview/Page/OverviewPageViewController.swift
  Wable-iOS/Presentation/Overview/Page/View/OverviewPageViewController.swift
  Wable-iOS/Presentation/Overview/Page/View/Subview/OverviewPageView.swift
  Wable-iOS/Presentation/Overview/Page/View/Subview/WableBadgeSegmentedControl.swift
  Wable-iOS/Presentation/Overview/Rank/Model/RankViewItem.swift
  Wable-iOS/Presentation/Overview/Rank/View/Cell/RankCell.swift
  Wable-iOS/Presentation/Overview/Rank/View/Cell/RankHeaderView.swift
  Wable-iOS/Presentation/Overview/Rank/View/RankListViewController.swift
  Wable-iOS/Presentation/Overview/Rank/ViewModel/RankViewModel.swift
  Wable-iOS/Presentation/WableComponent/Cell/GameTypeCell.swift
Labels: ✨ feat, ♻️ refactor, 🍻 진웅

#147 [Feat] 소셜 로그인 및 자동 로그인 기능 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Core/Bundle/Bundle+.swift
  Wable-iOS/Core/Logger/WableLogger.swift
  Wable-iOS/Data/RepositoryImpl/UserSessionRepositoryImpl.swift
  Wable-iOS/Domain/RepositoryInterface/UserSessionRepository.swift
  Wable-iOS/Domain/UseCase/Login/FetchUserAuthUseCase.swift
  Wable-iOS/Infra/Auth/AppleAuthProvider.swift
  Wable-iOS/Infra/Auth/KakaoAuthProvider.swift
  Wable-iOS/Infra/Local/KeychainStorage.swift
  Wable-iOS/Infra/Network/APIProvider.swift
  Wable-iOS/Infra/Network/MoyaLoggingPlugin.swift
  Wable-iOS/Infra/Network/OAuth/OAuthEventManager.swift
  Wable-iOS/Infra/Network/OAuth/OAuthenticator.swift
  Wable-iOS/Infra/Network/TargetType/BaseTargetType.swift
  Wable-iOS/Infra/Network/TargetType/ContentTargetType.swift
  Wable-iOS/Infra/Token/TokenStorage.swift
  Wable-iOS/Presentation/Home/HomeViewController.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Login/LoginViewModel.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Resource/Info.plist
Labels: ✨ feat, 🦉 유진

#150 [Fix] DIContainer 수정 및 소식 탭 앰플리튜드 태그 추가
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/App/AppDelegate+InjectDependency.swift
  Wable-iOS/App/AppDelegate.swift
  Wable-iOS/Core/DI/DIContainer.swift
  Wable-iOS/Presentation/Overview/Page/View/OverviewPageViewController.swift
Labels: 🛠️ fix, 🍻 진웅

#152 [Feat] Combine으로 Driver, Relay, asDriver 구현하기
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Presentation/Helper/Extension/Publisher+Driver.swift
  Wable-iOS/Presentation/Helper/Types.swift
  Wable-iOS/Presentation/Overview/Rank/View/RankListViewController.swift
  Wable-iOS/Presentation/Overview/Rank/ViewModel/RankViewModel.swift
Labels: ✨ feat, 🍻 진웅
