Repository Team-Wable/WABLE-iOS, pull requests merged in 2025-02, with the labels that each got.

#93 Refactor [#90] 상세보기 리팩토링 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Network/Home/HomeAPI.swift
  Wable-iOS/Network/Home/HomeRouter.swift
  Wable-iOS/Network/Home/ResponseDTO/HomeFeedListDTO.swift
  Wable-iOS/Presentation/Home/Model/FlattenReplyModel.swift
  Wable-iOS/Presentation/Home/Model/PopupModel.swift
  Wable-iOS/Presentation/Home/ViewController/HomePopupViewController.swift
  Wable-iOS/Presentation/Home/ViewController/MigratedDetailViewController.swift
  Wable-iOS/Presentation/Home/ViewController/MigratedHomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModels/MigratedDetailViewModel.swift
  Wable-iOS/Presentation/Home/ViewModels/MigratedHomeViewModel.swift
  Wable-iOS/Presentation/Home/ViewModels/PopupViewModel.swift
  Wable-iOS/Presentation/Home/Views/Cells/MigratedDetailCell.swift
  Wable-iOS/Presentation/Home/Views/Cells/MigratedHomeFeedCell.swift
  Wable-iOS/Presentation/Home/Views/MigratedDetailView.swift
  Wable-iOS/Presentation/Notification/Activity/ViewModel/NotificationActivityViewModel.swift
Labels: Refactor, 🍪윤빈

#95 Refactor [#94] 로그인 및 온보딩 코드 재구성 완료
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Application/SceneDelegate.swift
  Wable-iOS/Global/Literals/ImageLiterals.swift
  Wable-iOS/Global/Literals/StringLiterals.swift
  Wable-iOS/Global/Resources/Assets.xcassets/Team/bfx.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Team/bfx.imageset/image 3263.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/bfx.imageset/image 3263@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/bfx.imageset/image 3263@3x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/dnf.imageset/Contents.json
  Wable-iOS/Global/Resources/Assets.xcassets/Team/dnf.imageset/dnf.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/dnf.imageset/dnf@2x.png
  Wable-iOS/Global/Resources/Assets.xcassets/Team/dnf.imageset/dnf@3x.png
  Wable-iOS/Network/Foundation/APIConstants.swift
  Wable-iOS/Network/Foundation/URLSession/NetworkService.swift
  Wable-iOS/Network/Join/JoinAPI.swift
  Wable-iOS/Network/Join/JoinRouter.swift
  Wable-iOS/Network/Join/RequestDTO/UserInfoDTO.swift
  Wable-iOS/Network/SocialLogin/DTO/ResponseDTO/SocialLoginResponseDTO.swift
  Wable-iOS/Network/SocialLogin/LoginAPI.swift
  Wable-iOS/Network/SocialLogin/LoginRouter.swift
  Wable-iOS/Presentation/Home/Supports/Team.swift
  Wable-iOS/Presentation/Home/Views/Subviews/FeedInfoView.swift
  Wable-iOS/Presentation/Info/Ranking/Support/TeamRankMapper.swift
  Wable-iOS/Presentation/Info/Ranking/ViewController/InfoRankingViewController.swift
  Wable-iOS/Presentation/Join/View/JoinAgreementListCustomView.swift
  Wable-iOS/Presentation/Join/View/JoinAgreementView.swift
  Wable-iOS/Presentation/Join/View/JoinLCKTeamView.swift
  Wable-iOS/Presentation/Join/ViewController/JoinAgreementViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinLCKTeamViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinLCKYearViewController.swift
  Wable-iOS/Presentation/Join/ViewController/JoinProfileViewController.swift
  Wable-iOS/Presentation/Join/ViewController/MigratedJoinAgreementViewController.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinAgreementViewModel.swift
  Wable-iOS/Presentation/Join/ViewModel/JoinProfileViewModel.swift
  Wable-iOS/Presentation/Join/ViewModel/MigratedJoinAgreementViewModel.swift
  Wable-iOS/Presentation/Login/Support/SocialPlatform.swift
  Wable-iOS/Presentation/Login/ViewController/LoginViewController.swift
  Wable-iOS/Presentation/Login/ViewModel/MigratedLoginViewModel.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageAccountInfoViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageReplyViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageSignOutConfirmViewController.swift
  Wable-iOS/Presentation/MyPage/ViewController/MyPageViewController.swift
  Wable-iOS/Presentation/MyPage/ViewModel/MyPageProfileViewModel.swift
Labels: Refactor, 🍪윤빈

#97 Feat [#96] AuthenticationInterceptor를 이용한 토큰 관리 로직 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Data/RepositoryImpl/LoginRepositoryImpl.swift
  Wable-iOS/Domain/RepositoryInterface/LoginRepository.swift
  Wable-iOS/Infra/Network/APIProvider.swift
  Wable-iOS/Infra/Network/OAuth/OAuthCredential.swift
  Wable-iOS/Infra/Network/OAuth/OAuthErrorMonitor.swift
  Wable-iOS/Infra/Network/OAuth/OAuthTokenProvider.swift
  Wable-iOS/Infra/Network/OAuth/OAuthenticator.swift
  Wable-iOS/Infra/Network/TargetType/ContentLikedTargetType.swift
Labels: Feat, Network, 🦉 유진

#101 [Refactor] 도메인 엔티티 수정 및 보완
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/xcshareddata/xcschemes/Wable-iOS.xcscheme
  Wable-iOS/Data/Mapper/CommentMapper.swift
  Wable-iOS/Data/Mapper/ContentMapper.swift
  Wable-iOS/Data/Mapper/InformationMapper.swift
  Wable-iOS/Data/Mapper/NotificationMapper.swift
  Wable-iOS/Data/Mapper/ViewitMapper.swift
  Wable-iOS/Data/RepositoryImpl/ReportRepositoryImpl.swift
  Wable-iOS/Domain/Entity/AccountInfo.swift
  Wable-iOS/Domain/Entity/Announcement.swift
  Wable-iOS/Domain/Entity/Comment.swift
  Wable-iOS/Domain/Entity/Community.swift
  Wable-iOS/Domain/Entity/Content.swift
  Wable-iOS/Domain/Entity/GameSchedule.swift
  Wable-iOS/Domain/Entity/LCKTeamRank.swift
  Wable-iOS/Domain/Entity/Like.swift
  Wable-iOS/Domain/Entity/Notification.swift
  Wable-iOS/Domain/Entity/Opacity.swift
  Wable-iOS/Domain/Entity/TriggerType.swift
  Wable-iOS/Domain/Entity/User.swift
  Wable-iOS/Domain/Entity/Viewit.swift
  Wable-iOS/Domain/Enum/AccountDeleteReason.swift
  Wable-iOS/Domain/Enum/GameStatus.swift
  Wable-iOS/Domain/Enum/InfoNotificationType.swift
  Wable-iOS/Domain/Enum/LCKTeam.swift
  Wable-iOS/Domain/Enum/PostStatus.swift
  Wable-iOS/Domain/Enum/SocialPlatform.swift
  Wable-iOS/Domain/Enum/TriggerType.swift
  Wable-iOS/Domain/RepositoryInterface/ReportRepository.swift
  Wable-iOS/Resource/Info.plist
  Wable-iOS/Resource/ko.lproj/LaunchScreen.strings
Labels: Refactor, 🍻 진웅
