Repository Team-Wable/WABLE-iOS, pull requests merged in 2025-05, with the labels that each got.

#179 [Feat] 홈 화면 기능 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/Domain/Entity/Opacity.swift
  Wable-iOS/Domain/UseCase/Home/CreateBannedUseCase.swift
  Wable-iOS/Domain/UseCase/Home/CreateReportUseCase.swift
  Wable-iOS/Domain/UseCase/Home/FetchGhostUseCase.swift
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/Home/View/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Presentation/WableComponent/Cell/ContentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/ViewController/WableSheetViewController.swift
Labels: ✨ feat, 🦉 유진

#183 [Feat] 뷰잇 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/App/AppDelegate+InjectDependency.swift
  Wable-iOS/Core/DI/BuildConfiguration.swift
  Wable-iOS/Core/DI/DIContainer.swift
  Wable-iOS/Core/DI/Injected.swift
  Wable-iOS/Data/Mapper/ErrorMapper.swift
  Wable-iOS/Data/Mapper/ViewitMapper.swift
  Wable-iOS/Data/RepositoryImpl/ReportRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/URLPreviewRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/ViewitRepositoryImpl.swift
  Wable-iOS/Domain/Entity/URLPreview.swift
  Wable-iOS/Domain/Entity/Viewit.swift
  Wable-iOS/Domain/Enum/UserRole.swift
  Wable-iOS/Domain/RepositoryInterface/URLPreviewRepository.swift
  Wable-iOS/Domain/RepositoryInterface/ViewitRepository.swift
  Wable-iOS/Domain/UseCase/UserRole/CheckUserRoleUseCase.swift
  Wable-iOS/Domain/UseCase/Viewit/CreateViewitUseCase.swift
  Wable-iOS/Domain/UseCase/Viewit/LikeViewitUseCase.swift
  Wable-iOS/Domain/UseCase/Viewit/ReportViewitUseCase.swift
  Wable-iOS/Domain/UseCase/Viewit/ViewitUseCase.swift
  Wable-iOS/Infra/Network/DTO/Request/Viewit/CreateViewitPostRequest.swift
  Wable-iOS/Infra/Network/DTO/Response/Viewit/FetchViewits.swift
  Wable-iOS/Infra/Network/TargetType/ViewitTargetType.swift
  Wable-iOS/Presentation/Helper/Types.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Presentation/Viewit/Create/View/CreateViewitViewController.swift
  Wable-iOS/Presentation/Viewit/Create/View/Subview/ViewitInputView.swift
  Wable-iOS/Presentation/Viewit/Create/ViewModel/CreateViewitViewModel.swift
  Wable-iOS/Presentation/Viewit/List/Model/ViewitBottomSheetActionKind.swift
  Wable-iOS/Presentation/Viewit/List/View/Cell/ViewitListCell.swift
  Wable-iOS/Presentation/Viewit/List/View/Subview/ViewitListView.swift
  Wable-iOS/Presentation/Viewit/List/View/ViewitListViewController.swift
  Wable-iOS/Presentation/Viewit/List/ViewModel/ViewitListViewModel.swift
  Wable-iOS/Presentation/Viewit/ViewitViewController.swift
  Wable-iOS/Presentation/WableComponent/Button/LikeButton.swift
  Wable-iOS/Resource/Assets.xcassets/Button/btn_link_press.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Button/btn_link_press.imageset/btn_link_press.png
  Wable-iOS/Resource/Assets.xcassets/Button/btn_link_press.imageset/btn_link_press@2x.png
  Wable-iOS/Resource/Assets.xcassets/Button/btn_link_press.imageset/btn_link_press@3x.png
Labels: ✨ feat, 🍻 진웅

#185 [Fix] 온보딩 로직 수정
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/ProfileRegisterViewController.swift
Labels: 🛠️ fix, 🍻 진웅

#186 [Feat] FCM을 이용한 푸시 알림 기능 구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/App/AppDelegate+Firebase.swift
  Wable-iOS/App/AppDelegate.swift
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Data/Mapper/ContentMapper.swift
  Wable-iOS/Data/RepositoryImpl/AccountRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/ContentRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/ProfileRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/UserSessionRepositoryImpl.swift
  Wable-iOS/Domain/RepositoryInterface/ContentRepository.swift
  Wable-iOS/Domain/RepositoryInterface/ProfileRepository.swift
  Wable-iOS/Domain/RepositoryInterface/UserSessionRepository.swift
  Wable-iOS/Domain/UseCase/Home/FetchUserInformationUseCase.swift
  Wable-iOS/Domain/UseCase/Login/FetchUserAuthUseCase.swift
  Wable-iOS/Domain/UseCase/Onboarding/CreateUserProfileUseCase.swift
  Wable-iOS/Domain/UseCase/Onboarding/UpdateFCMTokenUseCase.swift
  Wable-iOS/Domain/UseCase/Profile/FetchContentInfoUseCase.swift
  Wable-iOS/Domain/UseCase/Profile/UpdateUserBadgeUseCase.swift
  Wable-iOS/Infra/Network/DTO/Response/Content/FetchContent.swift
  Wable-iOS/Infra/Network/TargetType/AccountTargetType.swift
  Wable-iOS/Infra/Token/TokenStorage.swift
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/Home/View/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModel/HomeDetailViewModel.swift
  Wable-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Login/LoginViewModel.swift
  Wable-iOS/Presentation/Notification/Activity/View/ActivityNotificationViewController.swift
  Wable-iOS/Presentation/Notification/Activity/ViewModel/ActivityNotificationViewModel.swift
  Wable-iOS/Presentation/Notification/Information/View/InformationNotificationViewController.swift
  Wable-iOS/Presentation/Notification/Page/View/NotificationPageViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/AgreementViewController.swift
  Wable-iOS/Presentation/Viewit/Create/View/Subview/ViewitInputView.swift
  Wable-iOS/Presentation/WableComponent/Cell/ContentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/Cell/NotificationCell.swift
  Wable-iOS/Presentation/WableComponent/Navigation/NavigationView.swift
  Wable-iOS/Resource/Base.lproj/LaunchScreen 2.storyboard
Labels: ✨ feat, 🦉 유진

#189 [Fix] QA 반영
  Wable-iOS/Data/Mapper/NotificationMapper.swift
  Wable-iOS/Data/RepositoryImpl/URLPreviewRepositoryImpl.swift
  Wable-iOS/Domain/Enum/TriggerType.swift
  Wable-iOS/Domain/UseCase/Viewit/CreateViewitUseCase.swift
  Wable-iOS/Presentation/Community/View/CommunityViewController.swift
  Wable-iOS/Presentation/Community/ViewModel/CommunityViewModel.swift
  Wable-iOS/Presentation/Notification/Activity/Model/ActivityNotification+.swift
  Wable-iOS/Presentation/Viewit/Create/View/CreateViewitViewController.swift
  Wable-iOS/Presentation/Viewit/Create/View/Subview/ViewitInputView.swift
  Wable-iOS/Presentation/Viewit/Create/ViewModel/CreateViewitViewModel.swift
  Wable-iOS/Presentation/Viewit/List/View/Cell/ViewitListCell.swift
  Wable-iOS/Presentation/Viewit/List/View/Subview/ViewitListView.swift
  Wable-iOS/Presentation/WableComponent/Cell/NotificationCell.swift
  Wable-iOS/Presentation/WableComponent/ViewController/LoadingViewController.swift
Labels: 🛠️ fix, 🍻 진웅

#192 [Fix] 1차 QA 반영
  Wable-iOS/Infra/Network/MoyaLoggingPlugin.swift
  Wable-iOS/Presentation/Helper/Extension/UIFont+.swift
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/Home/View/HomeViewController.swift
  Wable-iOS/Presentation/Home/View/WritePostViewController.swift
  Wable-iOS/Presentation/Home/ViewModel/HomeDetailViewModel.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Onboarding/Cell/LCKYearCollectionViewCell.swift
  Wable-iOS/Presentation/Onboarding/ViewController/AgreementViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/LCKYearViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/ProfileRegisterViewController.swift
  Wable-iOS/Presentation/Profile/My/View/Subview/MyProfileView.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Presentation/WableComponent/Button/CommentButton.swift
  Wable-iOS/Presentation/WableComponent/Button/GhostButton.swift
  Wable-iOS/Presentation/WableComponent/Button/LikeButton.swift
  Wable-iOS/Presentation/WableComponent/Cell/CommentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/Cell/ContentCollectionViewCell.swift
  Wable-iOS/Presentation/WableComponent/ViewController/LoadingViewController.swift
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_link.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_link.imageset/ic_link.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_link.imageset/ic_link@2x.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_link.imageset/ic_link@3x.png
Labels: 🛠️ fix, ♻️ refactor, 🦉 유진

#197 [Fix] 프로필 기능 개선 및 기타 오류 수정
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/App/AppDelegate+InjectDependency.swift
  Wable-iOS/Data/Mapper/CommentMapper.swift
  Wable-iOS/Data/RepositoryImpl/CommentRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/ContentLikedRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/ContentRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/GhostRepositoryImpl.swift
  Wable-iOS/Data/RepositoryImpl/ReportRepositoryImpl.swift
  Wable-iOS/Domain/RepositoryInterface/CommentRepository.swift
  Wable-iOS/Domain/RepositoryInterface/ContentLikedRepository.swift
  Wable-iOS/Domain/RepositoryInterface/ContentRepository.swift
  Wable-iOS/Domain/RepositoryInterface/GhostRepository.swift
  Wable-iOS/Domain/RepositoryInterface/ReportRepository.swift
  Wable-iOS/Presentation/Home/View/HomeViewController.swift
  Wable-iOS/Presentation/Overview/Detail/View/AnnouncementDetailViewController.swift
  Wable-iOS/Presentation/Profile/AlarmSetting/View/AlarmSettingViewController.swift
  Wable-iOS/Presentation/Profile/Component/ProfileInfoCell.swift
  Wable-iOS/Presentation/Profile/Component/ProfileSegmentedHeaderView.swift
  Wable-iOS/Presentation/Profile/Edit/ProfileEditViewController.swift
  Wable-iOS/Presentation/Profile/Model/ProfileEmptyCellItem.swift
  Wable-iOS/Presentation/Profile/Model/ProfileSegment.swift
  Wable-iOS/Presentation/Profile/Model/ProfileViewItem.swift
  Wable-iOS/Presentation/Profile/My/View/Cell/MyProfileEmptyCell.swift
  Wable-iOS/Presentation/Profile/My/View/MyProfileViewController.swift
  Wable-iOS/Presentation/Profile/My/ViewModel/MyProfileViewModel.swift
  Wable-iOS/Presentation/Profile/Other/View/Cell/OtherProfileEmptyCell.swift
  Wable-iOS/Presentation/Profile/Other/View/OtherProfileViewController.swift
  Wable-iOS/Presentation/Profile/Other/ViewModel/OtherProfileViewModel.swift
  Wable-iOS/Presentation/TabBar/TabBarController.swift
  Wable-iOS/Presentation/Viewit/List/View/ViewitListViewController.swift
  Wable-iOS/Presentation/Viewit/List/ViewModel/ViewitListViewModel.swift
  Wable-iOS/Presentation/WableComponent/Cell/CommentCollectionViewCell.swift
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_level_badge.imageset/Contents.json
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_level_badge.imageset/ic_level_badge.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_level_badge.imageset/ic_level_badge@2x.png
  Wable-iOS/Resource/Assets.xcassets/Icon/ic_level_badge.imageset/ic_level_badge@3x.png
Labels: 🛠️ fix, 🍻 진웅

#195 [Feat] FCM을 이용한 푸시 알림 기능 재구현
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS/App/AppDelegate+Firebase.swift
  Wable-iOS/App/AppDelegate.swift
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/Home/View/HomeViewController.swift
  Wable-iOS/Presentation/Home/ViewModel/HomeDetailViewModel.swift
  Wable-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Wable-iOS/Presentation/Login/LoginViewModel.swift
  Wable-iOS/Presentation/Notification/Activity/ViewModel/ActivityNotificationViewModel.swift
  Wable-iOS/Presentation/Onboarding/View/ProfileRegisterView.swift
  Wable-iOS/Presentation/Onboarding/ViewController/AgreementViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/LCKTeamViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/LCKYearViewController.swift
  Wable-iOS/Presentation/Onboarding/ViewController/ProfileRegisterViewController.swift
  Wable-iOS/Presentation/Profile/AlarmSetting/View/AlarmSettingViewController.swift
  Wable-iOS/Presentation/Profile/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  Wable-iOS/Presentation/Profile/My/View/MyProfileViewController.swift
  Wable-iOS/Presentation/Profile/Withdrawal/Guide/View/WithdrawalGuideViewController.swift
  Wable-iOS/Presentation/Viewit/Create/ViewModel/CreateViewitViewModel.swift
  Wable-iOS/Resource/Info.plist
Labels: ✨ feat, 🛠️ fix, ♻️ refactor, 🦉 유진

#201 [Feat] 강제 업데이트 기능 구현
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Resource/Info.plist
Labels: ✨ feat, ⚙️ setting, 🦉 유진

#202 [Refactor] Combine+UIKit, withLatestFrom 구현하기
  Wable-iOS.xcodeproj/project.pbxproj
  Wable-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Wable-iOS/Core/Combine+/Publisher+.swift
  Wable-iOS/Presentation/Helper/Extension/Combine+UIKit/CombineCompatible.swift
  Wable-iOS/Presentation/Helper/Extension/Combine+UIKit/Publishers+UIControlEvent.swift
  Wable-iOS/Presentation/Helper/Extension/Combine+UIKit/Publishers+UIControlProperty.swift
  Wable-iOS/Presentation/Helper/Extension/Combine+UIKit/Publishers+UIGesture.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
  Wable-iOS/Presentation/Overview/Rank/View/RankListViewController.swift
  Wable-iOS/Presentation/Viewit/Create/View/CreateViewitViewController.swift
  Wable-iOS/Presentation/Viewit/Create/View/Subview/ViewitInputView.swift
  Wable-iOS/Presentation/Viewit/Create/ViewModel/CreateViewitViewModel.swift
Labels: ♻️ refactor, 🍻 진웅

#206 [Fix] 프로필 화면 런타임 에러 해결
  Wable-iOS/Presentation/Profile/My/View/MyProfileViewController.swift
  Wable-iOS/Presentation/Profile/Other/View/OtherProfileViewController.swift
Labels: 🛠️ fix, 🍻 진웅

#209 [Fix] 2차 QA 반영
  Wable-iOS/Core/Literals/String/StringLiterals+ProfileSetting.swift
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/Home/View/WritePostViewController.swift
  Wable-iOS/Presentation/Profile/Edit/ProfileEditViewController.swift
Labels: 🛠️ fix, 🦉 유진

#218 [Fix] 최종 QA 반영
  Wable-iOS/App/SceneDelegate.swift
  Wable-iOS/Presentation/Home/View/HomeDetailViewController.swift
  Wable-iOS/Presentation/Home/View/WritePostViewController.swift
  Wable-iOS/Presentation/Login/LoginViewController.swift
Labels: 🛠️ fix, 🦉 유진
